# justfile

# Default recipe runs all VS Code setup tasks.
default: vscode

# ------------------------------------------------------------------------------
# [VSCODE] - Recipes for managing the VS Code environment
# ------------------------------------------------------------------------------

# Run all VS Code setup scripts in order.
vscode: vscode-prepare vscode-configs vscode-extensions
    @echo "✅ All VS Code setup tasks completed."

# Generate or update VS Code settings.
vscode-prepare:
    @echo "🚀 Preparing project requirements..."
    @node .vscode/scripts/prepare.mjs install

# Generate or update local config files (e.g., .editorconfig).
vscode-configs:
    @echo "🚀 Running Configuration manager..."
    @node .vscode/scripts/configs.mjs

# Generate or update the recommended extensions list.
vscode-extensions:
    @echo "🚀 Syncing vscode extensions..."
    @node .vscode/scripts/extensions.mjs sync
